In [6]:
pwd

'C:\\Users\\atmik\\Documents\\10 Machine Learning'

In [7]:
cd D:\Data Scientist\Data Entry\ML\ML Model Practice\08_Decision Tree

D:\Data Scientist\Data Entry\ML\ML Model Practice\08_Decision Tree


In [8]:
import pandas as pd
df = pd.read_csv("DecisionTree_salaries.csv")
print(df.to_string())

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


       company                  job     degree  salary
0       google      sales executive  bachelors       0
1       google      sales executive    masters       0
2       google     business manager  bachelors       1
3       google     business manager    masters       1
4       google  computer programmer  bachelors       0
5       google  computer programmer    masters       1
6   abc pharma      sales executive    masters       0
7   abc pharma  computer programmer  bachelors       0
8   abc pharma     business manager  bachelors       0
9   abc pharma     business manager    masters       1
10    facebook      sales executive  bachelors       1
11    facebook      sales executive    masters       1
12    facebook     business manager  bachelors       1
13    facebook     business manager    masters       1
14    facebook  computer programmer  bachelors       1
15    facebook  computer programmer    masters       1


In [9]:
inputs = df.drop('salary', axis = 'columns')
print(inputs)

       company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters


In [10]:
target = df['salary']    # df.salary   (can also be written)
print(target)

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary, dtype: int64


In [11]:
from sklearn.preprocessing import LabelEncoder
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [12]:
inputs['company_n'] = le_company.fit_transform(inputs['company'])
inputs['job_n'] = le_company.fit_transform(inputs['job'])
inputs['degree_n'] = le_company.fit_transform(inputs['degree'])
print(inputs)

       company                  job     degree  company_n  job_n  degree_n
0       google      sales executive  bachelors          2      2         0
1       google      sales executive    masters          2      2         1
2       google     business manager  bachelors          2      0         0
3       google     business manager    masters          2      0         1
4       google  computer programmer  bachelors          2      1         0
5       google  computer programmer    masters          2      1         1
6   abc pharma      sales executive    masters          0      2         1
7   abc pharma  computer programmer  bachelors          0      1         0
8   abc pharma     business manager  bachelors          0      0         0
9   abc pharma     business manager    masters          0      0         1
10    facebook      sales executive  bachelors          1      2         0
11    facebook      sales executive    masters          1      2         1
12    facebook     busine

In [13]:
inputs_n = inputs.drop(['company', 'job', 'degree'], axis = 'columns')
print(inputs_n)

    company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1


In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs_n, target, test_size = 0.1)

In [15]:
len(X_train)

14

In [16]:
len(X_test)

2

In [17]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(inputs_n, target)

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


DecisionTreeClassifier()

In [18]:
model.score(inputs_n, target)

1.0

In [19]:
model.predict([[2,2,1]])

array([0], dtype=int64)

In [21]:
model.predict([[2,0,1]])

array([1], dtype=int64)

In [ ]:
# OR we can do it as below

# Atmik has done it in another way using dummy variable

In [22]:
cd D:\Data Scientist\Data Entry\ML\ML Model Practice\08_Decision Tree

D:\Data Scientist\Data Entry\ML\ML Model Practice\08_Decision Tree


In [49]:
import pandas as pd
df = pd.read_csv('DecisionTree_salaries.csv')
df

company                  job     degree  salary
0       google      sales executive  bachelors       0
1       google      sales executive    masters       0
2       google     business manager  bachelors       1
3       google     business manager    masters       1
4       google  computer programmer  bachelors       0
5       google  computer programmer    masters       1
6   abc pharma      sales executive    masters       0
7   abc pharma  computer programmer  bachelors       0
8   abc pharma     business manager  bachelors       0
9   abc pharma     business manager    masters       1
10    facebook      sales executive  bachelors       1
11    facebook      sales executive    masters       1
12    facebook     business manager  bachelors       1
13    facebook     business manager    masters       1
14    facebook  computer programmer  bachelors       1
15    facebook  computer programmer    masters       1

In [32]:
df1 = pd.get_dummies(df, drop_first = True)
df1

salary  company_facebook  company_google  job_computer programmer  \
0        0                 0               1                        0   
1        0                 0               1                        0   
2        1                 0               1                        0   
3        1                 0               1                        0   
4        0                 0               1                        1   
5        1                 0               1                        1   
6        0                 0               0                        0   
7        0                 0               0                        1   
8        0                 0               0                        0   
9        1                 0               0                        0   
10       1                 1               0                        0   
11       1                 1               0                        0   
12       1                 1               0                        0   
13       1                 1               0                        0   
14       1                 1               0                        1   
15       1                 1               0                        1   

    job_sales executive  degree_masters  
0                     1               0  
1                     1               1  
2                     0               0  
3                     0               1  
4                     0               0  
5                     0               1  
6                     1               1  
7                     0               0  
8                     0               0  
9                     0               1  
10                    1               0  
11                    1               1  
12                    0               0  
13                    0               1  
14                    0               0  
15                    0               1

In [33]:
df1.shape

(16, 6)

In [48]:
X = df1.drop('salary', axis = 1)
y = df1['salary']
X.head()

company_facebook  company_google  job_computer programmer  \
0                 0               1                        0   
1                 0               1                        0   
2                 0               1                        0   
3                 0               1                        0   
4                 0               1                        1   

   job_sales executive  degree_masters  
0                    1               0  
1                    1               1  
2                    0               0  
3                    0               1  
4                    0               0

In [51]:
y.head()

0    0
1    0
2    1
3    1
4    0
Name: salary, dtype: int64

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 4)

In [38]:
len(X_train)

14

In [39]:
len(X_test)

2

In [42]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [43]:
model.predict(X_test)

array([1, 0], dtype=int64)

In [44]:
y_test

12    1
0     0
Name: salary, dtype: int64

In [45]:
model.score(X_test, y_test)

1.0

In [46]:
model.predict_proba(X_test)

array([[0., 1.],
       [1., 0.]])

In [50]:
model.predict([[0,1,0,0,1]])

array([1], dtype=int64)