In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [3]:
# Approach 1:

In [4]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\atmik\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [5]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9833333333333333

In [6]:
rf = RandomForestClassifier(n_estimators = 40)    # estimators is no. of trees
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.975925925925926

In [7]:
# Explaining KFold from examplt:

In [8]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [10]:
# Approach 2

In [11]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

print(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
print(get_score(SVC(), X_train, X_test, y_train, y_test))
print(get_score(RandomForestClassifier(n_estimators = 40), X_train, X_test, y_train, y_test))

0.9629629629629629
0.9833333333333333
0.9814814814814815


C:\Users\atmik\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
# Approach 3:

In [13]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [14]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(),  X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(),  X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators = 40),  X_train, X_test, y_train, y_test))
        
        


C:\Users\atmik\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\atmik\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [15]:
scores_lr

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [16]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [17]:
scores_rf

[0.9115191986644408, 0.9415692821368948, 0.9315525876460768]

In [18]:
# Approach 4:

In [ ]:
# cross_val_score(model, X, y, cv = 4)

In [19]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(), digits.data, digits.target, cv = 4)

C:\Users\atmik\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\atmik\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.93555556, 0.90423163, 0.94877506, 0.91759465])

In [20]:
cross_val_score(SVC(), digits.data, digits.target, cv = 4)

array([0.96222222, 0.96659243, 0.98218263, 0.95100223])

In [21]:
cross_val_score(RandomForestClassifier(n_estimators = 40), digits.data, digits.target, cv = 4)

array([0.92666667, 0.92427617, 0.97550111, 0.93095768])

In [22]:
# why we do K Fold Cross Validation?
# because to take the average of scores (which we generated using cross_val_score) and the 
# average score is the final score for the respective model. 

In [23]:
def avg_(model, num1, num2, num3, num4):
    print(model)
    return (num1 + num2 + num3 + num4)/4

avg_(RandomForestClassifier(n_estimators = 40), 0.93777778, 0.91091314, 0.95545657, 0.92650334)

RandomForestClassifier(n_estimators=40)


0.9326627075

In [24]:
# another way to do average
import numpy as np
np.average([0.93777778, 0.91091314, 0.95545657, 0.92650334])

0.9326627075